version: 1.0.{build}
before_build:
  - cd src
  - ps: $scripts =@()
  - ps: $path= Resolve-Path ./
  - ps: new-item "buildoutput"	-Force -ItemType Directory 
  - ps: Get-ChildItem (Join-Path ($path) \BuildScripts\*.ps1)  | ForEach { 		$scripts += $_.FullName	} 
  - ps: $scripts | ForEach { . $_} 
  - nuget restore

  # enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


environment:
  COVERALLS_REPO_TOKEN:
    secure: 7m6u4U6aBEF9AUPt6XP+4zCNAkPgc8IUF34QJZ0qxHqSMJbeNvNsfdKpblLCwtFX

build:
  project: src\TechFu.Nirvana.sln
  verbosity: minimal 
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true

# run open cover and push to coveralls
test_script: 
  - ps: run_analysis

artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'


deploy:
  provider: NuGet
  api_key:
    secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
  skip_symbols: false
  artifact: /.*\.nupkg/