version: 1.0.{build}

environment:
  xunitLocation:packages\xunit.runner.console.2.1.0\tools\xunit.console.exe
  testLocation:TechFu.Nirvana.Tests\bin\Debug\TechFu.Nirvana.Tests.dll
  searchdirs:-searchdirs:&quot;TechFu.Nirvana\bin\Debug&quot;
  register:-register:user
  outputFile:-output:coverage.xml
  openCverLocation:\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe

before_build:
  - cd src
  - nuget restore
build:
  project: src\TechFu.Nirvana.sln
  verbosity: minimal

after_test: 
# generate report for NUnit testing framework:
  -cmd:$env:openCverLocation -register:user -filter:"+[*]*" -target:"env:xunitLocation" -targetargs:"env:testLocation" env:searchdirs env:outputFile

# generate report for MSTest testing framework:
#    -cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:YOURPROJECT.Tests/bin/debug/YOURPROJECT.Tests.dll" -output:coverage.xml

  - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml