version: 2.0.{build}
before_build:
  - cd src

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '2.0.{build}'
  package_version: '2.0.{build}'
  assembly_version: '2.0.{build}'
  file_version: '2.0.{build}'
  informational_version: '2.0.{build}'



environment:
  COVERALLS_REPO_TOKEN:
    secure: 7m6u4U6aBEF9AUPt6XP+4zCNAkPgc8IUF34QJZ0qxHqSMJbeNvNsfdKpblLCwtFX


build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet restore Nirvana.sln
  - cmd: dotnet pack Nirvana.sln

# run open cover and push to coveralls
test_script: 
  - ps: run_analysis
after_test: 
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "BuildOutput\coverage.xml"
  

deploy:
  - provider: NuGet
    api_key:
        secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
    skip_symbols: false
    artifact: Nirvana/**/Nirvana.*.nupkg
  - provider: NuGet
    api_key:
        secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
    skip_symbols: false
    artifact: /.Nirvana.TestFramework\bin\Debug\**\Nirvana.TestFramework.*.nupkg
  - provider: NuGet
    api_key:
        secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
    skip_symbols: false
    artifact: /.Nirvana.AzureQueues\bin\Debug\**\Nirvana.AzureQueues.*.nupkg
  - provider: NuGet
    api_key:
        secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
    skip_symbols: false
    artifact: /.Nirvana.MongoProvider\bin\Debug\**\Nirvana.MongoProvider.*.nupkg
  - provider: NuGet
    api_key:
        secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
    skip_symbols: false
    artifact: /.Nirvana.JsonSerializer\bin\Debug\**\Nirvana.JsonSerializer.*.nupkg
  - provider: NuGet
    api_key:
        secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
    skip_symbols: false
    artifact: /.Nirvana.SqlProvider.Ef6\bin\Debug\**\Nirvana.SqlProvider.Ef6.*.nupkg
  - provider: NuGet
    api_key:
        secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
    skip_symbols: false
    artifact: /.Nirvana.SqlProvider.EfCore\bin\Debug\**\Nirvana.SqlProvider.EfCore.*.nupkg
  - provider: NuGet
    api_key:
        secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
    skip_symbols: false
    artifact: /.Nirvana.Web\bin\Debug\**\Nirvana.Web.*.nupkg
  - provider: NuGet
    api_key:
        secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
    skip_symbols: false
    artifact: /.Nirvana.Web\bin\Debug\**\Nirvana.Web.*.nupkg
