version: 1.0.{build}

environment:
  xunitLocation: packages\xunit.runner.console.2.1.0\tools\xunit.console.exe
  testLocation: TechFu.Nirvana.Tests\bin\Debug\TechFu.Nirvana.Tests.dll
  searchdirs: TechFu.Nirvana\bin\Debug
  outputFile: coverage.xml
  opencoverLocation: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
  coversallslocation: packages\coveralls.io.1.3.4\tools\coveralls.net.exe  
  COVERALLS_REPO_TOKEN:
    secure: 3GdseosXgFoKKGTlxCnx4ufignGtNLGgxWDDskoA/2lb2NlFqIo5B1i72NerCpY4
before_build:
  - cd src
  - nuget restore
  - echo ${opencoverLocation}
build:
  project: src\TechFu.Nirvana.sln
  verbosity: minimal
  
# run open cover and push to coveralls
test_script: 
  - echo: XUnit Location:${xunitLocation}
  - ${opencoverLocation} -register:user -filter:"+[*]*" -target:"${xunitLocation}" -targetargs:"${testLocation}" -searchdirs:"${searchdirs}" -output:${outputFile}
  - ${coversallslocation} --opencover ${outputFile}