version: 1.0.{build}

before_build:
  - cd src
  - ps: $scripts =@()
  - ps: $path= Resolve-Path ./
  - ps: Get-ChildItem (Join-Path ($path) \BuildScripts\*.ps1)  | ForEach { 		$scripts += $_.FullName	} 
  - ps: $scripts | ForEach { . $_} 
  - nuget restore

build:
  project: src\TechFu.Nirvana.sln
  verbosity: minimal
  
# run open cover and push to coveralls
test_script: 
  - ps: run_analysis
