version: 1.0.{build}
before_build:
  - cd src
  - ps: $scripts =@()
  - ps: $path= Resolve-Path ./
  - ps: new-item "buildoutput"	-Force -ItemType Directory 
  - ps: Get-ChildItem (Join-Path ($path) \BuildScripts\*.ps1)  | ForEach { 		$scripts += $_.FullName	} 
  - ps: $scripts | ForEach { . $_} 
  - nuget restore


environment:
  COVERALLS_REPO_TOKEN:
    secure: 7m6u4U6aBEF9AUPt6XP+4zCNAkPgc8IUF34QJZ0qxHqSMJbeNvNsfdKpblLCwtFX

build:
  project: src\TechFu.Nirvana.sln
  verbosity: minimal 
  parallel: true
after_build
  - nuget pack TechFu.Nirvana\TechFu.Nirvana.nuspec -Version $(version) -OutputDirectory buildoutput 
  
# run open cover and push to coveralls
test_script: 
  - ps: run_analysis

artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'


deploy:
  provider: NuGet
  api_key:
    secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
  skip_symbols: false
  artifact: \buildoutput\*.nupkg/
