version: 1.0.{build}

environment:
  xunitLocation: packages\xunit.runner.console.2.1.0\tools\xunit.console.exe
  testLocation: TechFu.Nirvana.Tests\bin\Debug\TechFu.Nirvana.Tests.dll
  searchdirs: -searchdirs:&quot;TechFu.Nirvana\bin\Debug&quot;
  register: -register:user
  outputFile: coverage.xml
  openCverLocation: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
  coversallslocation: packages\coveralls.io.1.3.4\tools\coveralls.net.exe

before_build:
  - cd src
  - nuget restore
build:
  project: src\TechFu.Nirvana.sln
  verbosity: minimal

after_test: 
# generate report for NUnit testing framework:
  -cmd:$env:openCverLocation -register:user -filter:"+[*]*" -target:"$env:xunitLocation" -targetargs:"$env:testLocation" $env:searchdirs -output:$env:outputFile
  -cmd:$env:coversallslocation --opencover $end:outputFile