version: 2.0.{build}
before_build:
  - cd src

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '2.0.{build}'
  package_version: '2.0.{build}'
  assembly_version: '2.0.{build}'
  file_version: '2.0.{build}'
  informational_version: '2.0.{build}'



environment:
  COVERALLS_REPO_TOKEN:
    secure: 7m6u4U6aBEF9AUPt6XP+4zCNAkPgc8IUF34QJZ0qxHqSMJbeNvNsfdKpblLCwtFX


build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet restore Nirvana.sln
  - cmd: dotnet pack Nirvana.sln

deploy:
  - provider: NuGet
    api_key:
        secure: asQXQRyoV5Zk6pKz/xeEfo+PJIwSWc+UP96zy1xW6TEgx0PqD6aQSMU/6by+WEB4
    skip_symbols: false
    artifact: **\*.nupkg